In [2]:
# Task 1: Creating Arrays
import numpy as np

one_d_array = np.arange(1, 16)
print(one_d_array)
print("Shape:", one_d_array.shape)
print("Size:", one_d_array.size)
print("Data type:", one_d_array.dtype)
print()

two_d_array = np.arange(1, 10).reshape(3, 3)
print(two_d_array)
print("Shape:", two_d_array.shape)
print("Size:", two_d_array.size)
print("Data type:", two_d_array.dtype)
print()

three_d_array = np.random.rand(3, 5, 3)
print(three_d_array)
print("Shape:", three_d_array.shape)
print("Size:", three_d_array.size)
print("Data type:", three_d_array.dtype)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Shape: (15,)
Size: 15
Data type: int64

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data type: int64

[[[0.73136894 0.19175549 0.3671646 ]
  [0.45515804 0.69754882 0.58877896]
  [0.93725421 0.55887294 0.62555432]
  [0.89969936 0.96143421 0.77181123]
  [0.64479527 0.63855028 0.56347887]]

 [[0.70344711 0.4020702  0.07703723]
  [0.68092317 0.22031559 0.59155488]
  [0.51500079 0.74919723 0.34650416]
  [0.51583058 0.23913262 0.08417693]
  [0.54056514 0.9904559  0.2405361 ]]

 [[0.75160103 0.17137237 0.51665224]
  [0.29889983 0.33877028 0.24959467]
  [0.60189946 0.60562881 0.95063607]
  [0.23975157 0.59152747 0.11341069]
  [0.09293118 0.38411744 0.96209776]]]
Shape: (3, 5, 3)
Size: 45
Data type: float64


In [3]:
# Task 2: Array Indexing and Slicing
data = [5, 15, 25, 35, 45, 55, 65, 75, 85]

print("Original data:", data)

print("First 3 elements:", data[:3])

print("All elements with step of 2:", data[::2])

print("Reverse Array:", data[::-1])


Original data: [5, 15, 25, 35, 45, 55, 65, 75, 85]
First 3 elements: [5, 15, 25]
All elements with step of 2: [5, 25, 45, 65, 85]
Reverse Array: [85, 75, 65, 55, 45, 35, 25, 15, 5]


In [4]:
# Task 3: Mathematical Operations
import numpy as np

array_a = np.random.randint(1, 20, 5)
array_b = np.random.randint(1, 20, 5)

print("Random array A:", array_a)
print("Random array B:", array_b)

array_sum = array_a + array_b
print("Sum of A and B:", array_sum)

array_sub = array_a - array_b
print("Subtraction of A and B:", array_sub)

array_mul = array_a * array_b
print("Multiplication of A and B:", array_mul)

array_div = array_a / array_b
print("Division of A and B:", array_div)
print()

dot_product = np.dot(array_a, array_b)
print("Dot product of A and B:", dot_product)

mean_a = np.mean(array_a)
median_a = np.median(array_a)
std_dev_a = np.std(array_a)
variance_a = np.var(array_a)

print("Mean of array A:", mean_a)
print("Median of array A:", median_a)
print("Standard Deviation of array A:", std_dev_a)
print("Variance of array A:", variance_a)

max_b = np.max(array_b)
min_b = np.min(array_b)
max_index_b = np.argmax(array_b)
min_index_b = np.argmin(array_b)

print("Maximum value in array B:", max_b, "at index", max_index_b)
print("Minimum value in array B:", min_b, "at index", min_index_b)

Random array A: [ 8 12  8 13  4]
Random array B: [ 9  4  9  3 12]
Sum of A and B: [17 16 17 16 16]
Subtraction of A and B: [-1  8 -1 10 -8]
Multiplication of A and B: [72 48 72 39 48]
Division of A and B: [0.88888889 3.         0.88888889 4.33333333 0.33333333]

Dot product of A and B: 279
Mean of array A: 9.0
Median of array A: 8.0
Standard Deviation of array A: 3.22490309931942
Variance of array A: 10.4
Maximum value in array B: 12 at index 4
Minimum value in array B: 3 at index 3


In [5]:
# Task 4: Reshaping and Transposing
import numpy as np

my_data = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 100, 111, 122])
print("Original 1D Array:")
print(my_data)
print("Shape:", my_data.shape)
print()

reshaped_2d = my_data.reshape(4, 3)
print("Reshaped to 2D (4x3):")
print(reshaped_2d)
print("Shape:", reshaped_2d.shape)
print()

reshaped_3d = my_data.reshape(2, 2, 3)
print("Reshaped to 3D (2x2x3):")
print(reshaped_3d)
print("Shape:", reshaped_3d.shape)
print()

transposed_2d = reshaped_2d.T
print("Transposed 2D Array:")
print(transposed_2d)
print("Shape:", transposed_2d.shape)


Original 1D Array:
[ 11  22  33  44  55  66  77  88  99 100 111 122]
Shape: (12,)

Reshaped to 2D (4x3):
[[ 11  22  33]
 [ 44  55  66]
 [ 77  88  99]
 [100 111 122]]
Shape: (4, 3)

Reshaped to 3D (2x2x3):
[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [100 111 122]]]
Shape: (2, 2, 3)

Transposed 2D Array:
[[ 11  44  77 100]
 [ 22  55  88 111]
 [ 33  66  99 122]]
Shape: (3, 4)


In [6]:
# Task 5: Boolean Masking and Filtering
import numpy as np

numbers = np.array([12, 45, 33, 27, 50, 41, 22, 18, 39, 29, 32, 47, 10, 26, 44])
print("Original Array:")
print(numbers)
print()

above_25 = numbers[numbers > 25]
print("Elements greater than 25:")
print(above_25)
print()

changed_numbers = numbers.copy()
changed_numbers[changed_numbers < 30] = 0
print("Array after replacing elements < 30 with 0:")
print(changed_numbers)
print()

count_five = np.sum(numbers % 5 == 0)
print("Number of elements divisible by 5:", count_five)


Original Array:
[12 45 33 27 50 41 22 18 39 29 32 47 10 26 44]

Elements greater than 25:
[45 33 27 50 41 39 29 32 47 26 44]

Array after replacing elements < 30 with 0:
[ 0 45 33  0 50 41  0  0 39  0 32 47  0  0 44]

Number of elements divisible by 5: 3


In [7]:
# Task 6: Working with Built-in Functions
import numpy as np

values = np.linspace(0, 1, 10)
print("Equally spaced values between 0 and 1:")
print(values)
print()

matrix = np.eye(4)
print("4x4 Identity Matrix:")
print(matrix)
print()

random_nums = np.array([23, 87, 45, 12, 90, 34, 56, 78, 65, 19, 38, 99, 5, 74, 81, 40, 67, 29, 10, 53])
print("Original Random Array:")
print(random_nums)
print()

sorted_nums = np.sort(random_nums)
print("Sorted Array:")
print(sorted_nums)
print()

top_5 = sorted_nums[-5:]
print("5 Largest Elements:")
print(top_5)


Equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Original Random Array:
[23 87 45 12 90 34 56 78 65 19 38 99  5 74 81 40 67 29 10 53]

Sorted Array:
[ 5 10 12 19 23 29 34 38 40 45 53 56 65 67 74 78 81 87 90 99]

5 Largest Elements:
[78 81 87 90 99]


In [8]:
# Task 7: Generic
import numpy as np
import time

matrix_a = np.random.rand(100, 100)
matrix_b = np.random.rand(100, 100)

start = time.time()

product = np.dot(matrix_a, matrix_b)

try:
    det = np.linalg.det(product)
    inv = np.linalg.inv(product)
    is_invertible = True
except np.linalg.LinAlgError:
    det = None
    inv = None
    is_invertible = False

end = time.time()
duration = end - start

print("Matrix multiplication completed.")
print("Determinant:", det)
print("Is Invertible:", is_invertible)
if is_invertible:
    print("Inverse matrix calculated.")
else:
    print("Inverse not possible (matrix is singular).")
print("Time taken: {:.4f} seconds".format(duration))


Matrix multiplication completed.
Determinant: -7.302748843991638e+50
Is Invertible: True
Inverse matrix calculated.
Time taken: 0.0053 seconds
